package com.ecoquest.app.ui.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color

// ── Default (EcoQuest Green) ─────────────────────────────
private val LightColorScheme = lightColorScheme(
    primary = Green30,
    onPrimary = Color.White,
    primaryContainer = Green95,
    onPrimaryContainer = Green10,
    secondary = Green50,
    onSecondary = Color.White,
    secondaryContainer = Green95,
    onSecondaryContainer = Green10,
    tertiary = Amber30,
    onTertiary = Color.White,
    tertiaryContainer = Amber90,
    onTertiaryContainer = Color(0xFF261900),
    error = Error40,
    onError = Color.White,
    errorContainer = Error90,
    onErrorContainer = Error10,
    background = SurfaceLight,
    onBackground = Neutral10,
    surface = Color.White,
    onSurface = Neutral10,
    surfaceVariant = Green95,
    onSurfaceVariant = Color(0xFF3D5E4A),
    outline = Color(0xFF7B9A7B),
    outlineVariant = Green90,
    inverseSurface = Neutral20,
    inverseOnSurface = Neutral95,
    inversePrimary = Green80,
    surfaceTint = Green30
)

private val DarkColorScheme = darkColorScheme(
    primary = Green80,
    onPrimary = DarkGreen20,
    primaryContainer = DarkGreen30,
    onPrimaryContainer = DarkGreen90,
    secondary = Green70,
    onSecondary = DarkGreen10,
    secondaryContainer = DarkGreen20,
    onSecondaryContainer = DarkGreen90,
    tertiary = Amber80,
    onTertiary = Color(0xFF261900),
    tertiaryContainer = Color(0xFF3E2A00),
    onTertiaryContainer = Amber90,
    error = Error80,
    onError = Error20,
    errorContainer = Error30,
    onErrorContainer = Error90,
    background = SurfaceDark,
    onBackground = Green90,
    surface = Color(0xFF1A2E1A),
    onSurface = Green90,
    surfaceVariant = DarkGreen20,
    onSurfaceVariant = Green80,
    outline = Color(0xFF6B8F6B),
    outlineVariant = DarkGreen30,
    inverseSurface = Green90,
    inverseOnSurface = DarkGreen10,
    inversePrimary = Green40,
    surfaceTint = Green80
)

// ── Bosque ───────────────────────────────────────────────
private val BosqueLightColorScheme = lightColorScheme(
    primary = ForestGreen30,
    onPrimary = Color.White,
    primaryContainer = ForestGreen95,
    onPrimaryContainer = ForestGreen10,
    secondary = ForestGreen50,
    onSecondary = Color.White,
    secondaryContainer = ForestGreen95,
    onSecondaryContainer = ForestGreen10,
    tertiary = ForestBrown30,
    onTertiary = Color.White,
    tertiaryContainer = ForestBrown90,
    onTertiaryContainer = Color(0xFF1E0A00),
    error = Error40,
    onError = Color.White,
    errorContainer = Error90,
    onErrorContainer = Error10,
    background = ForestGreen99,
    onBackground = ForestGreen10,
    surface = Color.White,
    onSurface = ForestGreen10,
    surfaceVariant = ForestGreen95,
    onSurfaceVariant = Color(0xFF3D5E3A),
    outline = Color(0xFF6B8F6B),
    outlineVariant = ForestGreen90,
    inverseSurface = Neutral20,
    inverseOnSurface = Neutral95,
    inversePrimary = ForestGreen80,
    surfaceTint = ForestGreen30
)

private val BosqueDarkColorScheme = darkColorScheme(
    primary = ForestGreen80,
    onPrimary = ForestDarkGreen20,
    primaryContainer = ForestDarkGreen30,
    onPrimaryContainer = ForestDarkGreen90,
    secondary = ForestGreen70,
    onSecondary = ForestDarkGreen10,
    secondaryContainer = ForestDarkGreen20,
    onSecondaryContainer = ForestDarkGreen90,
    tertiary = ForestBrown80,
    onTertiary = Color(0xFF1E0A00),
    tertiaryContainer = Color(0xFF3E2420),
    onTertiaryContainer = ForestBrown90,
    error = Error80,
    onError = Error20,
    errorContainer = Error30,
    onErrorContainer = Error90,
    background = SurfaceDark,
    onBackground = ForestGreen90,
    surface = Color(0xFF1A2E1A),
    onSurface = ForestGreen90,
    surfaceVariant = ForestDarkGreen20,
    onSurfaceVariant = ForestGreen80,
    outline = Color(0xFF6B8F6B),
    outlineVariant = ForestDarkGreen30,
    inverseSurface = ForestGreen90,
    inverseOnSurface = ForestDarkGreen10,
    inversePrimary = ForestGreen40,
    surfaceTint = ForestGreen80
)

// ── Atardecer ────────────────────────────────────────────
private val AtardecerLightColorScheme = lightColorScheme(
    primary = SunsetOrange50,
    onPrimary = Color.White,
    primaryContainer = SunsetOrange95,
    onPrimaryContainer = SunsetOrange10,
    secondary = SunsetPurple40,
    onSecondary = Color.White,
    secondaryContainer = SunsetPurple95,
    onSecondaryContainer = SunsetPurple20,
    tertiary = SunsetAmber30,
    onTertiary = Color.White,
    tertiaryContainer = SunsetOrange95,
    onTertiaryContainer = Color(0xFF1A0800),
    error = Error40,
    onError = Color.White,
    errorContainer = Error90,
    onErrorContainer = Error10,
    background = SunsetOrange99,
    onBackground = SunsetOrange10,
    surface = Color.White,
    onSurface = SunsetOrange10,
    surfaceVariant = SunsetOrange95,
    onSurfaceVariant = Color(0xFF5C3A20),
    outline = Color(0xFFA08060),
    outlineVariant = SunsetOrange90,
    inverseSurface = SunsetOrange20,
    inverseOnSurface = SunsetOrange95,
    inversePrimary = SunsetOrange80,
    surfaceTint = SunsetOrange50
)

private val AtardecerDarkColorScheme = darkColorScheme(
    primary = SunsetOrange80,
    onPrimary = SunsetOrange20,
    primaryContainer = SunsetOrange30,
    onPrimaryContainer = SunsetOrange90,
    secondary = SunsetPurple80,
    onSecondary = SunsetPurple20,
    secondaryContainer = SunsetPurple30,
    onSecondaryContainer = SunsetPurple90,
    tertiary = SunsetAmber80,
    onTertiary = Color(0xFF1A0800),
    tertiaryContainer = Color(0xFF3E2000),
    onTertiaryContainer = SunsetOrange90,
    error = Error80,
    onError = Error20,
    errorContainer = Error30,
    onErrorContainer = Error90,
    background = SunsetDarkBg,
    onBackground = SunsetOrange90,
    surface = SunsetDarkSurface,
    onSurface = SunsetOrange90,
    surfaceVariant = SunsetDarkSurfaceVariant,
    onSurfaceVariant = SunsetOrange80,
    outline = Color(0xFFA08060),
    outlineVariant = Color(0xFF4A3000),
    inverseSurface = SunsetOrange95,
    inverseOnSurface = SunsetOrange20,
    inversePrimary = SunsetOrange40,
    surfaceTint = SunsetOrange80
)

// ── Océano ───────────────────────────────────────────────
private val OceanoLightColorScheme = lightColorScheme(
    primary = OceanTeal40,
    onPrimary = Color.White,
    primaryContainer = OceanTeal95,
    onPrimaryContainer = OceanTeal10,
    secondary = OceanBlue40,
    onSecondary = Color.White,
    secondaryContainer = OceanTeal95,
    onSecondaryContainer = OceanTeal10,
    tertiary = OceanCoral40,
    onTertiary = Color.White,
    tertiaryContainer = OceanTeal95,
    onTertiaryContainer = Color(0xFF1A0800),
    error = Error40,
    onError = Color.White,
    errorContainer = Error90,
    onErrorContainer = Error10,
    background = OceanTeal99,
    onBackground = OceanTeal10,
    surface = Color.White,
    onSurface = OceanTeal10,
    surfaceVariant = OceanTeal95,
    onSurfaceVariant = Color(0xFF3D5E5A),
    outline = Color(0xFF6B9F9B),
    outlineVariant = OceanTeal90,
    inverseSurface = Neutral20,
    inverseOnSurface = Neutral95,
    inversePrimary = OceanTeal80,
    surfaceTint = OceanTeal40
)

private val OceanoDarkColorScheme = darkColorScheme(
    primary = OceanTeal80,
    onPrimary = OceanTeal20,
    primaryContainer = OceanTeal30,
    onPrimaryContainer = OceanTeal90,
    secondary = OceanBlue80,
    onSecondary = OceanTeal20,
    secondaryContainer = OceanTeal30,
    onSecondaryContainer = OceanBlue80,
    tertiary = OceanCoral80,
    onTertiary = Color(0xFF1A0800),
    tertiaryContainer = Color(0xFF3E1800),
    onTertiaryContainer = OceanTeal90,
    error = Error80,
    onError = Error20,
    errorContainer = Error30,
    onErrorContainer = Error90,
    background = OceanDarkBg,
    onBackground = OceanTeal90,
    surface = OceanDarkSurface,
    onSurface = OceanTeal90,
    surfaceVariant = OceanDarkSurfaceVariant,
    onSurfaceVariant = OceanTeal80,
    outline = Color(0xFF6B9F9B),
    outlineVariant = Color(0xFF004840),
    inverseSurface = OceanTeal95,
    inverseOnSurface = OceanTeal20,
    inversePrimary = OceanTeal40,
    surfaceTint = OceanTeal80
)

// ── Noche ────────────────────────────────────────────────
private val NocheLightColorScheme = lightColorScheme(
    primary = NightIndigo40,
    onPrimary = Color.White,
    primaryContainer = NightIndigo95,
    onPrimaryContainer = NightIndigo10,
    secondary = NightPurple40,
    onSecondary = Color.White,
    secondaryContainer = NightIndigo95,
    onSecondaryContainer = NightIndigo10,
    tertiary = NightAmber40,
    onTertiary = Color.White,
    tertiaryContainer = NightIndigo95,
    onTertiaryContainer = Color(0xFF1A1000),
    error = Error40,
    onError = Color.White,
    errorContainer = Error90,
    onErrorContainer = Error10,
    background = NightIndigo99,
    onBackground = NightIndigo10,
    surface = Color.White,
    onSurface = NightIndigo10,
    surfaceVariant = NightIndigo95,
    onSurfaceVariant = Color(0xFF3D40A0),
    outline = Color(0xFF7B80C0),
    outlineVariant = NightIndigo90,
    inverseSurface = Neutral20,
    inverseOnSurface = Neutral95,
    inversePrimary = NightIndigo80,
    surfaceTint = NightIndigo40
)

private val NocheDarkColorScheme = darkColorScheme(
    primary = NightIndigo80,
    onPrimary = NightIndigo20,
    primaryContainer = NightIndigo30,
    onPrimaryContainer = NightIndigo90,
    secondary = NightPurple80,
    onSecondary = NightPurple40,
    secondaryContainer = NightIndigo30,
    onSecondaryContainer = NightPurple80,
    tertiary = NightAmber80,
    onTertiary = Color(0xFF1A1000),
    tertiaryContainer = Color(0xFF3E2800),
    onTertiaryContainer = NightAmber80,
    error = Error80,
    onError = Error20,
    errorContainer = Error30,
    onErrorContainer = Error90,
    background = NightDarkBg,
    onBackground = NightIndigo90,
    surface = NightDarkSurface,
    onSurface = NightIndigo90,
    surfaceVariant = NightDarkSurfaceVariant,
    onSurfaceVariant = NightIndigo80,
    outline = Color(0xFF7B80C0),
    outlineVariant = Color(0xFF002060),
    inverseSurface = NightIndigo95,
    inverseOnSurface = NightIndigo20,
    inversePrimary = NightIndigo40,
    surfaceTint = NightIndigo80
)

// ── Flora ────────────────────────────────────────────────
private val FloraLightColorScheme = lightColorScheme(
    primary = FloraRose40,
    onPrimary = Color.White,
    primaryContainer = FloraRose95,
    onPrimaryContainer = FloraRose10,
    secondary = FloraLavender40,
    onSecondary = Color.White,
    secondaryContainer = FloraRose95,
    onSecondaryContainer = FloraRose10,
    tertiary = FloraLime40,
    onTertiary = Color.White,
    tertiaryContainer = FloraRose95,
    onTertiaryContainer = Color(0xFF0A2000),
    error = Error40,
    onError = Color.White,
    errorContainer = Error90,
    onErrorContainer = Error10,
    background = FloraRose99,
    onBackground = FloraRose10,
    surface = Color.White,
    onSurface = FloraRose10,
    surfaceVariant = FloraRose95,
    onSurfaceVariant = Color(0xFF5D3D60),
    outline = Color(0xFFA07B90),
    outlineVariant = FloraRose90,
    inverseSurface = Neutral20,
    inverseOnSurface = Neutral95,
    inversePrimary = FloraRose80,
    surfaceTint = FloraRose40
)

private val FloraDarkColorScheme = darkColorScheme(
    primary = FloraRose80,
    onPrimary = FloraRose20,
    primaryContainer = FloraRose30,
    onPrimaryContainer = FloraRose90,
    secondary = FloraLavender80,
    onSecondary = FloraRose20,
    secondaryContainer = FloraRose30,
    onSecondaryContainer = FloraLavender80,
    tertiary = FloraLime80,
    onTertiary = Color(0xFF0A2000),
    tertiaryContainer = Color(0xFF1E3000),
    onTertiaryContainer = FloraLime80,
    error = Error80,
    onError = Error20,
    errorContainer = Error30,
    onErrorContainer = Error90,
    background = FloraDarkBg,
    onBackground = FloraRose90,
    surface = FloraDarkSurface,
    onSurface = FloraRose90,
    surfaceVariant = FloraDarkSurfaceVariant,
    onSurfaceVariant = FloraRose80,
    outline = Color(0xFFA07B90),
    outlineVariant = Color(0xFF400030),
    inverseSurface = FloraRose95,
    inverseOnSurface = FloraRose20,
    inversePrimary = FloraRose40,
    surfaceTint = FloraRose80
)

private val themes = mapOf(
    "default" to Pair(LightColorScheme, DarkColorScheme),
    "bosque" to Pair(BosqueLightColorScheme, BosqueDarkColorScheme),
    "atardecer" to Pair(AtardecerLightColorScheme, AtardecerDarkColorScheme),
    "oceano" to Pair(OceanoLightColorScheme, OceanoDarkColorScheme),
    "noche" to Pair(NocheLightColorScheme, NocheDarkColorScheme),
    "flora" to Pair(FloraLightColorScheme, FloraDarkColorScheme)
)

@Composable
fun EcoQuestMobileTheme(
    darkTheme: Boolean = false,
    themeName: String = "default",
    content: @Composable () -> Unit
) {
    val pair = themes[themeName] ?: themes["default"]!!
    val colorScheme = if (darkTheme) pair.second else pair.first

    MaterialTheme(
        colorScheme = colorScheme,
        typography = Typography,
        content = content
    )
}
